version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: hotel-availability-postgres
    environment:
      POSTGRES_DB: hotel_availability
      POSTGRES_USER: hotel_app
      POSTGRES_PASSWORD: hotel_app
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hotel_app -d hotel_availability"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - hotel-availability-net

  kafka:
    image: apache/kafka:3.8.0
    container_name: hotel-availability-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 15
    networks:
      - hotel-availability-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-availability-app
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: hotel_availability
      DB_USERNAME: hotel_app
      DB_PASSWORD: hotel_app
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - hotel-availability-net

volumes:
  postgres-data:

networks:
  hotel-availability-net:
    driver: bridge
